package jdbc;

public class DbSetting {

	public DbSetting() {
		DbManager.db.setData(""
				+ "-- MySQL Script generated by MySQL Workbench\n"
				+ "-- Fri Apr 21 20:15:38 2023\n"
				+ "-- Model: New Model    Version: 1.0\n"
				+ "-- MySQL Workbench Forward Engineering\n"
				+ "\n"
				+ "SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;\n"
				+ "SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;\n"
				+ "SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';\n"
				+ "\n"
				+ "-- -----------------------------------------------------\n"
				+ "-- Schema manager\n"
				+ "-- -----------------------------------------------------\n"
				+ "DROP SCHEMA IF EXISTS `manager` ;\n"
				+ "\n"
				+ "-- -----------------------------------------------------\n"
				+ "-- Schema manager\n"
				+ "-- -----------------------------------------------------\n"
				+ "CREATE SCHEMA IF NOT EXISTS `manager` DEFAULT CHARACTER SET utf8 ;\n"
				+ "USE `manager` ;\n"
				+ "\n"
				+ "-- -----------------------------------------------------\n"
				+ "-- Table `manager`.`user`\n"
				+ "-- -----------------------------------------------------\n"
				+ "CREATE TABLE IF NOT EXISTS `manager`.`user` (\n"
				+ "  `num` INT NOT NULL AUTO_INCREMENT,\n"
				+ "  `id` VARCHAR(45) NULL,\n"
				+ "  `pw` VARCHAR(45) NULL,\n"
				+ "  `name` VARCHAR(5) NULL,\n"
				+ "  `phoneNumber` VARCHAR(11) NULL,\n"
				+ "  PRIMARY KEY (`num`))\n"
				+ "ENGINE = InnoDB;\n"
				+ "\n"
				+ "\n"
				+ "SET SQL_MODE=@OLD_SQL_MODE;\n"
				+ "SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;\n"
				+ "SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;\n"
				+ ""
				+ "insert into manager.user(id, pw, name, phoneNumber) value (\"user01\", \"user01\", \"홍길동\", \"01011111111\");\n"
				+ "insert into manager.user(id, pw, name, phoneNumber) value (\"user02\", \"user02\", \"박힘찬\", \"01022222222\");\n"
				+ "insert into manager.user(id, pw, name, phoneNumber) value (\"user03\", \"user03\", \"박민우\", \"01033333333\");\n"
				+ "insert into manager.user(id, pw, name, phoneNumber) value (\"user04\", \"user04\", \"김정서\", \"01044444444\");\n"
				+ "insert into manager.user(id, pw, name, phoneNumber) value (\"user05\", \"user05\", \"박지후\", \"01055555555\");"
				+ ""
				+ "");
		
	}

}
